remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

website: https://blocky.github.io

title: [Blocky Experiments]
description: [Blog Site for Experiments & Results]

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"